protobuf_sources(
    name = "protos",
    python_source_root = "python/packages/messages/src",
    sources = ["definitions/**/*.proto"],
)


# protobuf_sources(
#     name = "protos",
#     python_resolve = parametrize("prod", "dev"),
#     python_source_root = "python/packages/messages/src",
#     sources = ["definitions/**/*.proto"],
# )
